### ISSUE TITLE
Add support for providing `-replace` flags in terraform plan module

### ISSUE THREAD

**Issue by toast-gear** [dflook/terraform-github-actions#110]
I need the ability to define resources to be replaced via the [-replace](https://www.terraform.io/docs/cli/commands/plan.html#replace-address) flag when using the `dflook/terraform-plan`. In my case I need to tag 4 lambdas to be replaced when a version is bumped. This is a blocker for me using this excellent action suite on a couple of pipelines 😞 

I believe the `-replace` flag doesn't take multiple values so we'll need to take the input, split it and build the argument again with each resource path prefixed with `-replace   ` .

Probably a new input e.g. `replace_resource_paths:`, decide on a delimiter e.g. a comma, add to the existing argument builder function to split the new input by the delimiter and rebuild it with each item prefixed with `-replace` https://github.com/dflook/terraform-github-actions/blob/master/image/actions.sh#L190 

https://github.com/hashicorp/terraform/releases/tag/v0.15.4 replace was added in 0.15.4 so I don't know if you want to include some validation of the terraform version or just let the error bubble up

**Comment by dflook** [comment]
A `replace` input was added in v1.18.0. I've created issue #119 for inspecting the state file
