### ISSUE TITLE
Improve clarity of the debug diff output

### ISSUE THREAD

**Issue by toast-gear** [dflook/terraform-github-actions#128]
We've had a plan fail to apply on a repository due to a drift between the plan on the PR and the plan at runtime, not super sure why atm as the repository doesn't have a busy bit of Terraform in it and the PR is merged more or less straight away but the output which is intended to help wasn't super clear to me without enabling step debug output.

When there is a dift in the runtime plan compared to the PR plan a diff is output `##[debug] diff /tmp/plan.txt /tmp/approved-plan.txt`. This output is helpful however it isn't clear that that's what the output is without step debug output enabled. The current message output is the below:

```
Not applying the plan - it has changed from the plan on the PR
The plan on the PR must be up to date. Alternatively, set the auto_approve input to 'true' to apply outdated plans
Plan changes:
```

It would nice if `Plan changes:` was changed to something more explicit like `Diff between plans below:`. Feel free to make it something else but the current message output confused me until I enabled the step debug output.

**Comment by toast-gear** [comment]
Ref https://github.com/dflook/terraform-github-actions/issues/132

**Comment by dflook** [comment]
This has been improved in v1.23.0
