### ISSUE TITLE
action dflook/terraform-plan don't mask sensitive variables when add comments to the PR

### ISSUE THREAD

**Issue by GiuseppeChiesa-TomTom** [dflook/terraform-github-actions#130]
I've noticed that when the `add_github_comment` is true, the variables reported in the comment on the Pull Request might contain sensitive data. 

I think the action should either mask the variables that are considered sensitive from terraform.

**Comment by dflook** [comment]
Yes, this is planned soon. This is noted in [the docs](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#inputs). If you set a `label`, then the variables won't be shown in the comment.

**Comment by erzz** [comment]
Just ran into this myself for the first time :)

I much prefer the layout of the comments when a label is not set.

e.g. 

**nice and clear what exactly plan is based on**
![image](https://user-images.githubusercontent.com/58994586/149787281-7fa89fc2-3847-482f-8f2c-3f9ccf31b514.png)
 
**missing important info in my opinion**
![image](https://user-images.githubusercontent.com/58994586/149787746-45130ea0-dedb-4b0c-9f55-4b388b6a9284.png)

Ideal for me we would have the no-label layout with anything either marked sensitive in the terraform config or coming from a github secret masked?

**Comment by JelleSmet-TomTom** [comment]
> Yes, this is planned soon. This is noted in [the docs](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#inputs). If you set a `label`, then the variables won't be shown in the comment.

@dflook I could find the reference in the documentation but I'm afraid I have no idea what this means ... 
could you give an example on how to modify the below such that the content of `secret` is not visible in the PR comment?
```
... snip ...
    - name: Terraform Plan
      uses: dflook/terraform-plan@v1.25.1
      id: terraform-plan
      with:
        path: .github/_scratch/xxxxxxxxxxx
        variables: |-
        name =  "some value"
        secret = "${{ secrets.MY_SECRET_VALUE }}"
... snip ...
```

**Comment by JelleSmet-TomTom** [comment]
Oh ok, I'll try this out tomorrow. It's somewhat odd/not intuitive this cause & effect exists.
Tnx @dflook for the project & support

**Comment by JelleSmet-TomTom** [comment]
Hi @dflook I'm afraid I can't seem to achieve that by setting a `label` value?

So to summarize and to be clear, the behavior should be:

Terraform variables which have the `sensitive` property set will have their value masked in the pull request comment added by the dflook action once a random value is assigned to the `label` parameter of the `dflook/terraform-plan` and `dflook/terraform-apply` actions.

**Comment by dflook** [comment]
There is no masking at all at the moment. Without a label, the comment contains the variables. With a label, the comment contains only the label.

**Comment by JelleSmet-TomTom** [comment]
ok got it .. thank you so much for clarifying!

**Comment by dflook** [comment]
v1.31.0 has been released which masks sensitive variables in the PR comment
