### ISSUE TITLE
Use with Terraform Cloud

### ISSUE THREAD

**Issue by efpe** [dflook/terraform-github-actions#134]
I tried to use the `output` action with Terraform Cloud by setting the API key. 

The code was able to call `terraform init` successfully but it failed when it tried to switch to a workspace. I believe the reason is that workspaces are different for local installations and cloud runs.

Any idea on how I could make this work?

Many thanks!

Links: 
- https://www.terraform.io/docs/cloud/workspaces/index.html
- https://github.com/dflook/terraform-github-actions/blob/master/image/entrypoints/output.sh#L9
- https://github.com/dflook/terraform-github-actions/blob/master/image/actions.sh#L191-L208

**Comment by dflook** [comment]
Hello @efpe, can you show your workflow yaml?

Can you also enable debug logging by setting the `ACTIONS_STEP_DEBUG` secret to `true` and the show the relevant logs?

Does the `terraform-apply` action work with the same workspace? `terraform-output` does the same thing as `terraform-apply`, so it's odd that `terraform-output` would fail.

**Comment by dflook** [comment]
Hi @efpe, I found an issue when using the `remote` backend with a fixed workspace `name` (rather than a `prefix`).
This should be fixed in v1.20.1, can you give it a try?

**Comment by efpe** [comment]
Thanks @dflook for the quick updates and fixes. I was and still out - I will definitely check in a couple of days and confirm the fix

Again, many thanks!
