### ISSUE TITLE
terraform apply not working

### ISSUE THREAD

**Issue by tb102122** [dflook/terraform-github-actions#14]
Hey dflook,

sorry but I am facing another issue. I am using the terraform-plan and terraform-apply with comments but the apply is not working.
I even compared the plans and the result is the same.
Any idea what could be wrong?
The plans are identical when I compare the different plan versions in the GITHUB action bot record.

![image](https://user-images.githubusercontent.com/62531735/90220727-189c5200-de4c-11ea-91c1-fc936d4dcae6.png)

Message at the end of the comment:
Plan not applied in apply #20 (Plan has changed)

Thanks for your help.

**Comment by dflook** [comment]
Do either of the plans have a message about obtaining/releasing the state lock at the beginning or end? They only appear of its taking a while, but could cause the plans not to match.

**Comment by tb102122** [comment]
Hey Daniel,

both of the plans have the following ending.

Plan: 4 to add, 9 to change, 4 to destroy.
Releasing state lock. This may take a few moments...

Between the plan and apply there is some time between the runs due to the jobs I need to run before for some packaging tasks.

**Comment by tb102122** [comment]
I also tried the approach with "Apply PR approved plans: is the same result. How can i debug it further to see what is the root cause? Can it be that the result is different due to the timestamps of some artifacts I have to build before the TF apply? I am creating some zip files which are used later on to create lambda functions via TF. So I have to use the following element as part of a TF module.

`# Initialize lambda variables

locals {
  codebase_root_path = abspath("${path.root}/..")
  lambda_package_zip = "${local.codebase_root_path}/${var.function_folder}/${var.function_folder}.zip"
  function_details   = split("_", var.function_folder)
  function_name      = join("_", slice(local.function_details, 0, length(local.function_details) - 1))
  lambda_key         = "${local.function_name}/${var.function_folder}.zip"
}

#-------------------------------------------------------------------------------
# Upload lambda function to S3
#-------------------------------------------------------------------------------
resource "aws_s3_bucket_object" "file_upload" {
  bucket = var.lambda_s3_bucket_name
  key    = local.lambda_key
  source = local.lambda_package_zip
  etag   = fileexists(local.lambda_package_zip) ? filemd5(local.lambda_package_zip) : null
}`

**Comment by dflook** [comment]
If the zip file is being recreated or updated between the plan or apply, then it looks like that's your issue.
Can you confirm by comparing the plan generated in the `plan` workflow log with the plan in the `apply` workflow log?

Typically zip files are different every time due to timestamps and file ordering. You could try something like [deterministic-zip](https://pypi.org/project/deterministic-zip/) to create an identical zip file every time unless the contents really has changed.

Another solution could be to generate and store the zip file somewhere and use the same file for both the plan and apply.

As a last resort, the `auto_approve` option of the apply action will apply any changes every time without checking the PR comment is still accurate.

**Comment by tb102122** [comment]
In the plan I don't see the difference of the hash it is the same.
I will give it a try with a different approach for handling the zip files to see if that resolves the issue. 
The auto-approval I can set via an env variable of your action?

**Comment by tb102122** [comment]
Hey Daniel,

thanks again for your help.
The problem was related to the zip file, the changes of the zip-files are not shown in the plan output since the hash values is the same between the different runs.
I resolved the issue using the following action.

https://github.com/dawidd6/action-download-artifact

Cheers Tobi
