### ISSUE TITLE
Terraform release lock command

### ISSUE THREAD

**Issue by noam-ma-ma** [dflook/terraform-github-actions#176]
### Suggestion

Using automation tools to run terraform is great, but sometimes jobs get cancelled and leaves the lock in tf state.

It would be great to have an action release lock - giving the lock-id as input

**Comment by dflook** [comment]
Interesting idea @noam-ma-ma. Where would you get the lock-id from?

**Comment by noam-ma-ma** [comment]
Running terraform plan/apply when lock exists prints the lock to the console: 
![Screen Shot 2022-04-25 at 22 03 14](https://user-images.githubusercontent.com/71635658/165156919-db0e833e-2cc6-48cf-abb0-8a147ba51f3a.png)

**Comment by dflook** [comment]
The [dflook/terraform-state-unlock](https://github.com/dflook/terraform-github-actions/tree/main/terraform-state-unlock) action was added in v1.32.0
