### ISSUE TITLE
Provide an option to ignore warnings when comparing plans

### ISSUE THREAD

**Issue by toast-gear** [dflook/terraform-github-actions#177]
### Suggestion

**Problem Statement**
We've found Terraform isn't determanistic about what order it shows warnings in. We get plans fail fairly often due to diffs in the warnings between the PR plan vs the execution plan even though the actual resources and their changes in the plan are identical. We've raised an issue with terraform for it https://github.com/hashicorp/terraform/issues/30934. 

**Solution**
Create a new setting in dflook/terraform-apply for configuring if the diff check considers warnings or not as part of the diff (true as default for backwards compatibility if you like although I'm not sure why you'd want to consider them given they aren't deterministic). If true then any difference causes a fail, if false only diffs which don't contain warnings fail. Feels doable if a bit complicated, perhaps output the json too into a hidden comment and compare against that? Or perhaps we can jsut filter out warnings as part of the compare

**Comment by dflook** [comment]
Hi @toast-gear, warnings are now ignored when comparing plans in v1.27.0.
