### ISSUE TITLE
This is probably user error but I'm not sure

### ISSUE THREAD

**Issue by ksgriggs** [dflook/terraform-github-actions#18]
I'm trying to get the demo running that you show in https://github.com/dflook/terraform-github-actions/tree/master/terraform-apply.

The terraform-plan runs correctly and the plan is put into the PR but after merging the branches the terraform apply fails.  I must be missing something.  Here is part of the output from the action.

```
Terraform has been successfully initialized!
Applying plan in [Apply terraform plan #11](https://github.com/ksgriggs/terraform-pr-validate/actions/runs/234868125)
Unable to update status on PR
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

null_resource.nill: Refreshing state... [id=1781873233465892696]
null_resource.nada: Refreshing state... [id=9146469937314840400]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.zip will be created
  + resource "null_resource" "zip" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
Approved plan not found
```

If you have any suggestions they would be greatly appreciated.

**Comment by dflook** [comment]
Hi, thanks for creating an issue!

I would check that all the input values for the plan and apply actions are the same - `path`, `workspace` etc. If they don't match, the apply won't be able to find the plan.

If that doesn't help, try setting the `ACTIONS_STEP_DEBUG` secret to `true`. This will output more information to the workflow log, which may be useful.

**Comment by ksgriggs** [comment]
The plan and apply actions both only have `path` set.  Both set to terraform which is where backend.tf and main.tf are located.
I'll set `ACTIONS_STEP_DEBUG` and see what the extra logging provides.  How is the plan passed from the plan action to the apply action?

Thank you for your time with this.

**Comment by ksgriggs** [comment]
It was user error.  I feel stupid now.  I was creating a github token and using that but github actions has a default token that I should have been using.  Now that I've deleted my token it works as I expect.  Thank you for taking the time to respond earlier.  You can close this issue.

**Comment by dflook** [comment]
Glad it's working for you now. There is an assumption that you are using the default token, but I'll think about how to make it work with a provided token.
