### ISSUE TITLE
Add support for Kubectl

### ISSUE THREAD

**Issue by kripplek** [dflook/terraform-github-actions#183]
### Suggestion

Currently using these to provision Kubernetes clusters and within the clusters configure them with TF.

I really don't want to separate this functionality out into separate repositories. 

Can we add kubctl/aws to the base docker image?

```
Error: Get "https://XXXXXXXXXXXX.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

  with module.eks.kubernetes_config_map_v1_data.aws_auth[0],
  on /tmp/terraform-data-dir/modules/eks/main.tf line 431, in resource "kubernetes_config_map_v1_data" "aws_auth":
 431: resource "kubernetes_config_map_v1_data" "aws_auth" {
 ```

**Comment by dflook** [comment]
Hi @kripplek, you can use the `TERRAFORM_PRE_RUN` environment variable to install any tools you need.
See [dflook/terraform-plan](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#environment-variables) for an example.
