### ISSUE TITLE
Allow setting of Git config settings within Action container

### ISSUE THREAD

**Issue by yardbirdsax** [dflook/terraform-github-actions#204]
### Suggestion

I have a rather unusual situation and wanted to see if there is a more graceful way to handle this than what I've already done before submitting a PR.

The setup is this: I have a Terraform module repository that itself contains a Git sub-module, and the sub-module is referenced with an SSH style URL (e.g. `git@github.com:org/sub-module-repo`). The module reference itself (in the `.tf` file) uses an HTTPs style Git URL (e.g. `git::https://github.com/org/module`). Both of these are private repositories. Using the existing `TERRAFORM_HTTP_CREDENTIALS` env var, I can get the initial clone of the module to work, however when it tries to check out the submodule (because `go-getter`, the library used by Terraform, [always checks out submodules](https://github.com/hashicorp/go-getter/blob/293f9e2372e5cd5ff8cdf7b6977b861122837292/get_git.go#L143)), it fails because it still tries to use SSH to clone it, and there's no available SSH key to use.

While I'll could probably try and PR an enhancement to that library to allow disabling of that "always check out submodules" functionality (and subsequently Terraform to use the updated library), that's going to take a bit of time. In the meantime, the only way I've gotten this to work is by setting the global Git configuration to use an `insteadOf` directive that replaces `git@github` URLs with `https://github.com` ones. You can see how I did this with a new input [here](https://github.com/yardbirdsax/terraform-github-actions/blob/eba72b1284d5ac638b56b54702b7f127d7040f39/terraform-plan/action.yaml#L52), and a change to the shared `actions.sh` script's `setup` function [here](https://github.com/yardbirdsax/terraform-github-actions/blob/add-git-insteadof/image/actions.sh#L83). Since this is all in a container I don't _think_ it would affect anything beyond the run itself (i.e. it's not going to muck with the global Git config on the runner).

Is there a better way to do this? If not, happy to submit a PR from my fork with this new functionality. Thanks!

**Comment by dflook** [comment]
Hi @yardbirdsax, you could set the [`TERRAFORM_SSH_KEY`](https://github.com/dflook/terraform-github-actions/tree/main/terraform-plan#environment-variables) environment variable to allow terraform to checkout the ssh submodule.

If thats not possible, I would suggest making your git config changes using the [`TERRAFORM_PRE_RUN`](https://github.com/dflook/terraform-github-actions/tree/main/terraform-plan#environment-variables) script environment variable.

**Comment by yardbirdsax** [comment]
Well duh, that (the `TERRAFORM_PRE_RUN` environment variable; we don't use SSH keys for Git access from GitHub Actions) would work now wouldn't it. Shame on me for not reading the lovely README. 😄 Thanks, this worked perfectly! I'll close the issue.
