### ISSUE TITLE
Providers used during plan might be different than the providers used during apply

### ISSUE THREAD

**Issue by tony-aq** [dflook/terraform-github-actions#208]
### Suggestion

We have some conditions of apply running with updated providers after the plan has run successful some days previous.

Technically, the versions of providers allow newer provider versions - but sometimes newer provider versions come along with state changes that need to be approved.

If the plan provider versions matched the apply provider versions, it would remove a main source of differences we run into.

Maybe this is more of a terraform request, where the plan detail should take into account the provider versions... idk.

**Comment by glenthomas** [comment]
Isn't this exactly what the [Dependency Lock File](https://developer.hashicorp.com/terraform/language/files/dependency-lock) is for?

**Comment by rdhar** [comment]
Reckon this one's already addressed/resolved by existing functionality within Terraform's lock file itself.

**Comment by dflook** [comment]
This can be addressed by using a lock file, or specifying stricter provider version constraints.
This would only be an issue if the latest provider version matching the constraints changed between the plan and apply, and the new version has changed the resource representation.

Closing as I don't think there is anything in particular we need to do here.
