### ISSUE TITLE
Support AWS cli for kubernetes provide auth

### ISSUE THREAD

**Issue by gionn** [dflook/terraform-github-actions#209]
### Problem description

Hello, some terraform provider requires external tooling to be available on PATH, like with [kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins).

It is fine to add the aws cli into the Docker image used by all of these actions? Best would be to have the possibility to configure which version of the aws cli to install.

### Workflow log

```shell
Error: Kubernetes cluster unreachable: Get "https://*.yl4.us-west-1.eks.amazonaws.com/version": getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

**Comment by dflook** [comment]
You can use the [`TERRAFORM_PRE_RUN`](https://github.com/dflook/terraform-github-actions/tree/main/terraform-plan#environment-variables) environment variable to install whatever tools you need.

**Comment by gionn** [comment]
Completely missed that, thanks!
