### ISSUE TITLE
`set-output` deprecation warning

### ISSUE THREAD

**Issue by bogi0704** [dflook/terraform-github-actions#212]
### Suggestion

Running the apply action results in a new deprecation warning:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The set-output command is being used in /image/workflow_commands.sh, line 63.

**Comment by dflook** [comment]
Thanks @bogi0704, this is fixed in v1.28.0
