### ISSUE TITLE
ARM support for the image

### ISSUE THREAD

**Issue by szymonpk** [dflook/terraform-github-actions#226]
### Suggestion

We are using your image mostly for fmt check. Is there any chance you could add support for the ARM architecture? I am not sure how hard could it be. I would not bother you, but IIRC, we cannot specify custom image for the action, right?

**Comment by dflook** [comment]
Hello @szymonpk, an ARM image should be doable.

Do you need to run terraform on ARM specifically, or are you just looking to use existing ARM self-hosted runners?

**Comment by szymonpk** [comment]
For now the later, we are trying to run arm-only infrastructure. But we would like to support both use-cases at some point.

**Comment by dflook** [comment]
The image is now built for arm64, starting in v1.34.0

**Comment by szymonpk** [comment]
Thanks @dflook! It works ;-)
