### ISSUE TITLE
Request: Plan and apply with destroy and refresh flags

### ISSUE THREAD

**Issue by rdhar** [dflook/terraform-github-actions#242]
### Suggestion

Hey there, big thank you for sharing this suite -- far exceeds the official offering from Hashicorp itself!

As I'm integrating these actions into various workflows, there's a couple of optional flags which'd be greatly appreciated if they were included with `plan` and `apply` commands. For `-refresh`, I've shared my reasoning in the open PR #205. For `-destroy`, this would be ideal as part of a PR review workflow.

For example, after you're done with a temporary workspace (which spans a few different branches so isn't quite as short-lived as "ephemeral" testing ones), I'd like to destroy/delete it without having to remove or comment out the TF configuration itself. By using `terraform plan -destroy` (see [docs](https://developer.hashicorp.com/terraform/cli/commands/destroy)), we can preview the expected output from `destroy` before proceeding normally with your "terraform-destroy-workspace" action. Please let me know if I can help provide any more info here. 

Thanks once again for your time.

**Comment by dflook** [comment]
Hello @rdhar, I think adding a `destroy: true` input for the plan and apply actions makes sense. This would allow planning and applying destroy mode plans in the same way as normal plans.

**Comment by rdhar** [comment]
Greatly appreciated, thank you!
