### ISSUE TITLE
Terraform plan with: workspace enhancement

### ISSUE THREAD

**Issue by dstrates** [dflook/terraform-github-actions#245]
### Suggestion

Currently the `with: workspace:` option selects the given workspace, and fails if the workspace doesn't exist. Should this instead create the workspace if missing?

**Comment by rdhar** [comment]
I think the approach here is to make each GitHub Action atomic in its functionality. So it's up to the user to setup their workflow accordingly, pick-and-choosing which bit they'd like. 

In my case, I resolved to check whether the workflow will operate on a non-default workspace and, if so, then initialise it first. On subsequent runs, even if the non-default workspace has been already initialised, re-initialising it again does no harm and just adds a few more seconds to the workflow execution time. 

Here's the [relevant snippet](https://github.com/o11y-top/aws-terraform-multiple-environments/blob/main/.github/workflows/terraform.yml#L96-L99).

```terraform
# Initialise terraform workspace if one is specified.
- name: Terraform workspace
  if: env.tf_workspace != 'default'
  uses: dflook/terraform-new-workspace@v1
  with:
    workspace: ${{ env.tf_workspace }}
    path: environments/${{ env.tf_environment }}
    …
```
