### ISSUE TITLE
The default run pulls the latest terraform binary if unspecified 

### ISSUE THREAD

**Issue by sjortiz** [dflook/terraform-github-actions#249]
### Suggestion

# Description
Tags should be fixed to a terraform version, to prevent the code from breaking if terraform pushes a breaking change at any point.

Also one of the modules I have has a hard dependency in the previous version (can be removed I think, but that proves more work than benefits in this case), regardless, the default behavior for tags should be said tag is fixed to a binary

**Comment by dflook** [comment]
If you require a specific terraform version, you need to specify what version it is. See the [dflook/terraform-version](https://github.com/dflook/terraform-github-actions/tree/main/terraform-version) docs for the different ways it can be set.

**Comment by sjortiz** [comment]
I know that sir, my comment is that tags should be fixed to specific versions :) or you can have a tag that one day works and not the other because the python code in this repo can be meet with a breaking change.
