### ISSUE TITLE
Docker pull rate limit

### ISSUE THREAD

**Issue by rdhar** [dflook/terraform-github-actions#250]
### Problem description

Hey there, thanks again for sharing this GitHub Actions! 
I've been continuously running into Docker's pull rate limit today since around 17:30 UTC:

```log
Pull down action image 'danielflook/terraform-github-actions@sha256:1a65b03b960c8737dce51e74faf1482322bffc6fba5177288489f101086f9c75'
  /usr/bin/docker pull danielflook/terraform-github-actions@sha256:1a65b03b960c8737dce51e74faf1482322bffc6fba5177288489f101086f9c75
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  Warning: Docker pull failed with exit code 1, back off 1.888 seconds before retry.
```

First off, are there some suggested workarounds for this? 

And, assuming that authenticating our workflow with [docker/login-action](https://github.com/docker/login-action) is one of them, which registry is the image hosted on? 

Cheers,
Rishav

**Comment by dflook** [comment]
The action image is pulled during job setup, i.e before before any docker/login-action can run. The image is hosted on dockerhub. 

I understood there to be an agreement between github and dockerhub to allow github hosted runners to pull public images without login or rate limit. Are you using a self-hosted runner?

**Comment by rdhar** [comment]
Ah shoot, I hadn't realised that the rate limit shouldn't apply in these circumstances. 

You're spot-on, I _am_ using a self-hosted runner just for specific internal/proxy access. I guess it's on me to use the regular GitHub-hosted runners in that case, since we can't run docker/login-action on a previous step?

**Comment by dflook** [comment]
I guess if you can login with docker-engine on the machine hosting the runner, that would increase the rate limit.
I don't know what would happen if you later need to run `docker/login-action` in a job on that runner.

Even when logged in the rate limit is quite low. When dockerhub's rate limiting was introduced I started pushing the image to a GitHub image registry just in case, but there is no way to choose which registry to use from the released actions.

**Comment by rdhar** [comment]
And I guess if we're after a "bullet-proof" approach with self-hosting our own image, I reckon that's not really an option available to us (addressed in #223) ?

**Comment by dflook** [comment]
I have added new `-ghcr` release tags starting with v1.34.0 that use the GitHub container registry. These look like:

`dflook/terraform-plan@v1.34.0-ghcr`
`dflook/terraform-plan@v1.34-ghcr`
`dflook/terraform-plan@v1-ghcr`

I can't find any definitive usage limits for github container registry, it seems like usage from any actions runner may be unlimited. It does seem to be slightly slower than dockerhub though.

**Comment by rdhar** [comment]
Oh neat, thank you! What's the process for giving those a go instead?

**Comment by dflook** [comment]
It's a bit awkward, update the 'version' for every action, e.g:

```yaml
      - name: terraform plan
        uses: dflook/terraform-plan@v1-ghcr
        with:
          path: my-terraform-config
```

**Comment by rdhar** [comment]
That's not so bad at all, all things considered. If anything, great to have a fallback option just in case. Thanks for making this available!
