### ISSUE TITLE
plan output color

### ISSUE THREAD

**Issue by JafoFett** [dflook/terraform-github-actions#259]
### Suggestion

Would it be possible to get the plan output color to be green for "create" and red for "destroy" in the PR comments? I know there are limitations with Github markup language, so maybe this is it. It almost looks like you set the output to be HCL for the markup text...just curious if it's possible.

**Comment by dflook** [comment]
It is not possible as far as I know, the best you can do is use the syntax highlighting blocks like `hcl`. Comments also have a maximum size and every option I've explored for coloring plans would use up a lot of it, meaning long plans would have trouble fitting in the comment.

**Comment by JafoFett** [comment]
Thanks for the response.

**Comment by F21** [comment]
I was wondering if it would be possible to implement this using `diff` highlighting. It's a feature that's available in the unmaintained `terraform-pr-commenter` action: https://github.com/robburger/terraform-pr-commenter/blob/master/entrypoint.sh#L189

This blog post also has an implementation: https://blog.testdouble.com/posts/2021-12-07-elevate-your-terraform-workflow-with-github-actions/#re-introduce-colors

**Comment by dflook** [comment]
Hi @F21, using diff formatting looks like a good option
