### ISSUE TITLE
PR comments are empty with Terraform 0.14.0

### ISSUE THREAD

**Issue by sarkis** [dflook/terraform-github-actions#26]
@dflook thanks for this great github action, really happy I stumbled upon it! 😄
 
I noticed that the PR plan comment is no longer working and it lines up with the Terraform 0.14 release. I assume that there was changes due to the new feature of concise plans (https://www.hashicorp.com/blog/announcing-hashicorp-terraform-0-14-general-availability). 

I was trying to help with a PR, but didn't realize how involved it is getting a copy of the github action forked. I assume the issue is somewhere here: https://github.com/sarkis/terraform-github-actions/commit/5e99a98d3a19ead7672db4a0e0760f6446e08105

or at least that is where I was going to start looking... Happy to provide any other info you require.

**Comment by dflook** [comment]
Thanks @sarkis, it looks like we no longer need the sed line with the new 0.14 plan.

I'll work on getting a fix out.

**Comment by sarkis** [comment]
@dflook confirmed! I was finally able to test from my own fork of the action, it is fixed for me with the following diff: https://github.com/sarkis/terraform-github-actions/commit/6f07cb379c2405dffefa6d3781783328d643fa8d

Though, I am wondering do we need the tf-mask related stuff now 🤔, I guess it's good to stay there for pre 0.14.0 compatibility... 🚀

**Comment by dflook** [comment]
@sarkis This is fixed in v1.5.1
