### ISSUE TITLE
Update .tfstate with terraform apply

### ISSUE THREAD

**Issue by coyotespike** [dflook/terraform-github-actions#260]
### Suggestion

Howdy! I love these tools a lot. Currently I use terraform plan, and then comment `terraform apply` to actually apply the changes.

However, after creating resources, terraform will complain on another apply that the resources already exist. Is there a way to have the runner save tfstate with the results of apply, as of course happens locally?

Thanks for any ideas!

**Comment by dflook** [comment]
Typically you would use a [state backend](https://developer.hashicorp.com/terraform/language/settings/backends/configuration) to store the state file.

If that's not possible, you should be able to commit the changed state file back to the repo from within a run step.

**Comment by coyotespike** [comment]
Thanks @dflook! Currently I'm using git-crypt to allow the runner to decrypt the file. Thanks for the suggestion, I'll add some steps to the workflow to commit back the state file.
