### ISSUE TITLE
Attach output from apply command

### ISSUE THREAD

**Issue by rdhar** [dflook/terraform-github-actions#263]
### Suggestion

Hi there, many thanks for sharing this versatile suite of workflows!

#### Request

One feature that'd be greatly appreciated would be the ability to print the terraform log after applying a plan in the PR comment.

**Comment by rdhar** [comment]
#### Reasons

* Outputs which are known after `terraform apply` are hidden behind the workflow link, instead of being revealed in situ with the PR. For this reason, I thought the current behaviour is a bug since it made sense to update/replace the contents of `terraform plan` with `terraform apply` to have the entire history of changes accessible conveniently.
* Workflow run logs have a limited retention period, whereas, PR comments can keep `terraform apply`'s log for longer, in case of audit compliance. 
* Given the real-time plan status notifications (i.e., Applying plan in…) on the PR comment, it seems that the same webhook can be leveraged to update the comment with `terraform apply'` output seamlessly.

What do you reckon?

**Comment by rdhar** [comment]
No longer required as I found a solution in [DevSecTop/TF-via-PR](https://github.com/devsectop/tf-via-pr) repository, which hosts a reusable workflow to run Terraform commands via PR comments, like a CLI.

[Here's an example](https://github.com/devsectop/tf-via-pr/pull/121) of how the output of the workflow looks when triggered by PR comments input.

**Comment by henworth** [comment]
I'd personally still like to see this as an option.

**Comment by rdhar** [comment]
Agreed, it'd be great to have the option to view the outcome of the apply action.

@henworth If you're interested in a different approach, [TF Via PR Comments](https://github.com/marketplace/actions/tf-via-pr-comments) is available on the GitHub Action Marketplace. This is what its `apply` output response looks like (or [view the PR conversation](https://github.com/devsectop/tf-via-pr-comments/pull/166) for yourself).

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/dflook/terraform-github-actions/assets/19497993/85840d83-a748-480a-8439-957cfb3b92c3">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/dflook/terraform-github-actions/assets/19497993/460dab01-e656-441a-a074-3502e336a472">
  <img alt="Screenshot of the author's TF command in a PR comment followed by github-action bot's TF output response in the next comment." src="https://github.com/dflook/terraform-github-actions/assets/19497993/85840d83-a748-480a-8439-957cfb3b92c3">
</picture>

**Comment by dflook** [comment]
This issue has become confused. Is this about showing the terraform output values in the comment after an apply operation?

**Comment by rdhar** [comment]
The output values are included as part of apply, so it'd be great to have the entire log of the apply operation returned on the PR comment.

**Comment by henworth** [comment]
> This issue has become confused. Is this about showing the terraform output values in the PR comment after an apply operation?

Happy to make a new issue if that helps. That's what I'd love to see be supported, surfacing the outputs in the PR comment.
