### ISSUE TITLE
Cosmetic - missing the selected workspace name

### ISSUE THREAD

**Issue by DanyC97** [dflook/terraform-github-actions#277]
### Problem description

Since the introduction of https://github.com/dflook/terraform-github-actions/pull/268 a minor/ cosmetic issue was spotted where the selected workspace is no longer shown in the GHA job logs.

![image](https://github.com/dflook/terraform-github-actions/assets/7383422/0e9721c7-b24e-4933-a5e0-70d013921ec5)

However, i can confirm the right workspace is being used by comparing with the TFC state file mapped to the expected workspace.

### Terraform version

1.4.5

### Backend

cloud

**Comment by DanyC97** [comment]
I'm aware of the comment https://github.com/dflook/terraform-github-actions/pull/268/files#diff-056fbb78c8b4523a7f9db9a9af7b63e75c0dd5b50cb150934844938db259f635R254, i think a simple echo will do to let user know the value since we know it / set in the export ?

**Comment by DanyC97** [comment]
Fixed https://github.com/dflook/terraform-github-actions/pull/278 

thank you @dflook  for quick response! (will keep an eye for when you cut a new release)

**Comment by dflook** [comment]
This is fixed in 1.36.1 🎉
