### ISSUE TITLE
Support for Terraform 1.6 test framework

### ISSUE THREAD

**Issue by oboukili** [dflook/terraform-github-actions#294]
### Suggestion

First, thanks for all your work !

Terraform 1.6 introduced a new [built-in test framework](https://developer.hashicorp.com/terraform/language/tests#tests), it would be great if we could have a github action that supported this.

**Comment by dflook** [comment]
Hello, v1.43.0 has been released which includes the new `dflook/terraform-test` and `dflook/tofu-test` actions.
