### ISSUE TITLE
Add option to create new comments on following execution of a terraform operation

### ISSUE THREAD

**Issue by gusfcarvalho** [dflook/terraform-github-actions#296]
### Suggestion

As of today, the terraform-github-actions always tries to find an existing comment to update it (https://github.com/dflook/terraform-github-actions/blob/main/image/src/github_pr_comment/comment.py#L342-L350). For specially big plans, this means that a track is lost on what a given commit caused the terraform plan / apply to do.

For tracking purposes, setting a flag to specify multiple comments to be created for a single plan would allow for a clean track record and to be able to quickly identify what was the commit that introduced/fixed a given bug.

**Comment by dflook** [comment]
Hi @gusfcarvalho, thanks for creating an issue. I can see how this could be useful.

**Comment by rileygriffith** [comment]
Bumping this issue, would like to see this change as well

**Comment by dflook** [comment]
With v1.38.0, the `add_github_comment` input for `dflook/terraform-plan` can be set to `always-new`, which will cause every generated plan to be in a new PR comment.
