### ISSUE TITLE
Relative module paths

### ISSUE THREAD

**Issue by crmitchelmore** [dflook/terraform-github-actions#32]
Firstly, thank you! I'm new to TF and have struggled with automation so far. This is so much of an upgrade to all the other automation approaches I've looked at: Azure pipelines, tflcoud, Atlantis. Very very happy to have discovered this <3

I have modules in the same project as my main module (likely will move them out eventually but I find it much easier to iterate this way) e.g.
```
module "resource_group_service_principal" {
  source          = "../modules/azure-service-principal"
}
```

But this fails on the plan step:

```
Error: Unreadable module directory
Unable to evaluate directory symlink: lstat ../modules: no such file or directory
```

Going to have a crack at fixing this but thought I'd raise this for reference and if anyone has any quick solutions.

**Comment by dflook** [comment]
Hi @crmitchelmore, I'm glad this is useful for you!

I can only think that the module source path is not right. Does it work when running terraform locally?

**Comment by crmitchelmore** [comment]
Well that's embarrassing! Managed to move the folder somehow 

![giphy](https://user-images.githubusercontent.com/1902403/108481899-a7bd7300-7290-11eb-94d6-97c8a33d7d47.gif)

Thanks again
