### ISSUE TITLE
Sensitive variable exposed in Plan added as a comment on the PR

### ISSUE THREAD

**Issue by shariqmus** [dflook/terraform-github-actions#342]
### Suggestion

When we add a variable like this to the action:

```
          variables: |
            api_token = "${{ secrets.API_KEY }}"
```

this variable's value is exposed. Anyway to hide the sensitive variable value?

**Comment by dflook** [comment]
Hello @shariqmus, if the variable is defined with `sensitive = true` like [described here](https://developer.hashicorp.com/terraform/language/values/variables#suppressing-values-in-cli-output) it should be masked in the PR comment.

Do you have an example where this is not working?

**Comment by shariqmus** [comment]
Thanks for your response,

After adding the variable as sensitive = true in terraform code, the secret was not printed

```
variable "api_token" {
  type = string
  sensitive = true
}
```
