### ISSUE TITLE
Complex Terraform input variables are not supported with 'var' action input

### ISSUE THREAD

**Issue by donovanmuller** [dflook/terraform-github-actions#35]
If you try set complex Terraform [inputs](https://www.terraform.io/docs/language/values/variables.html#variables-on-the-command-line), like lists or maps containing a comma, in the `var` action [input](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#inputs) to plan/apply actions, the `var` value is not parsed correctly.

It appears the basic handling in [`set-plan-args`](https://github.com/dflook/terraform-github-actions/blob/145468bdefe29401837f15b17576661d47b4e8cf/image/actions.sh#L149) of the comma separator splits up the complex values incorrectly:

```console
$ # Working basic example
$ INPUT_VAR=test1=1,test2=2
$ echo "$INPUT_VAR" | tr ',' '\n'
test1=1
test2=2

$ # Complex list var value gets split in half
$ INPUT_VAR=test1=1,test2=[test2_1=2_1,test2_2=2_2]
$ echo "$INPUT_VAR" | tr ',' '\n'
test1=1
test2=[test2_1=2_1
test2_2=2_2]
```

As you can see from the example above, the `test2` var value gets split in two, where the expected value would be:

```console
$ # Expected value
$ INPUT_VAR=test1=1,test2=[test2_1=2_1,test2_2=2_2]
$ echo "$INPUT_VAR" | tr ',' '\n'
test1=1
test2=[test2_1=2_1,test2_2=2_2]
```

**Comment by donovanmuller** [comment]
A workaround is to set `TF_VAR_` as an environment variable:

```yaml
        env:
          TF_VAR_test2: "[test2_1=2_1,test2_2=2_2]"
```

**Comment by dflook** [comment]
v1.9.0 has a new `variables` input that supports complex values.

```yaml
      - name: Plan
        uses: dflook/terraform-plan@v1
        with:
          variables: |
            num_instances=1
            zones=["a", "b", "c"]
```

`var` is now deprecated.
