### ISSUE TITLE
terraform-version should also infer the version from TFC/TFE workspace

### ISSUE THREAD

**Issue by nikolay** [dflook/terraform-github-actions#38]
There are too many "sources of truth" when it comes to which Terraform version to use. All tools completely ignore the commercial version of Terraform and the ability of remote runs, which use the version specified in the TFC/TFE workspace, and don't care about `tfenv`, `tfswitch`, and the version constraint in the plan.

**Comment by dflook** [comment]
Hello @nikolay, I agree there are too many places to specify the version!

I see the `required_version` constraint is the right way to control the terraform version. The `tfenv` and `tfswitch` tools pre-date the constraint and are supported for compatibility. The tools are useful for switching between versions while developing.

How I understand Terraform Cloud is that the version for a workspace is set by the version of terraform that created it, so is initially controlled by the `required_version`. If created in the UI, it defaults to the latest version.

When planning or applying `remote` workspaces, the version specified in the workspace is used regardless of the local version.
If you are always working with `remote` workspaces that already exist, I would suggest not specifying the version anywhere else. The action will default to the latest version of the terraform, but the remote will use whatever version is configured there.

You are right that the `terraform-version` output may be wrong though. Can you tell me more about what you are using it for?

**Comment by nikolay** [comment]
The `required_version` is a constraint, not a concrete version. The issue is that the state version can be upgraded to a newer version. I guess, maybe I just need to use `terraform state pull | jq -r '.terraform_version'` if `.terraform_version` does not exist, which would give the state's exact Terraform version. Unfortunately, it is slow like any other TFC operation.

**Comment by wagnst** [comment]
Correct, the version is set on the workspace, `required_version` has nothing to do with the actual version from it.

**Comment by dflook** [comment]
Hello @wagnst, the workspace version can be set by the version of terraform that created it, so the `required_version` certainly has something to do with it.

Perhaps you can help me understand the use case?

**Comment by wagnst** [comment]
@dflook when using terraform enterprise or terraform cloud (which we do: https://www.terraform.io/docs/cloud/workspaces/index.html) the terraform version is set on the workspace level (where the execution of terraform happens, not in the actions). So terraform enterprise sets the version of terraform basically. In your detection mechanism you should probably add a function to read out the terraform version from the workspace that the execution happens.
You can create free version of TfC at https://app.terraform.io for playing around with it (it works the same on Terraform Enterprise).

**Comment by dflook** [comment]
The `terraform-version` action determines the terraform and provider versions to use for a terraform configuration directory.
When no terraform version is specified the latest version is used, which should work with any remote workspace.
Have you encounted a situation where this does not work?

It sounds like you want to know the terraform version set in a TFC workspace, can you please tell me what you would use it for?

**Comment by wagnst** [comment]
@dflook we use it for running linting and things on actions (locally) and the actual plan and apply happens remote on the workspace. But both runs (local in actions and remote on TfC) shall use the same TF version, hence it would be nice if the `terraform-version` one could determine the remote workspace TF version as well before falling back to latest.

**Comment by dflook** [comment]
This was added in v1.22.0. 

If the module uses Terraform Cloud/Enterprise and the workspace exists then the terraform version set in the remote workspace is used. The token will need to be available in `TERRAFORM_CLOUD_TOKENS`.
