### ISSUE TITLE
Support pull_request_target event type

### ISSUE THREAD

**Issue by pputerla** [dflook/terraform-github-actions#42]
Hello,

I would like to request/or/propose support for event type called _pull_request_target_
The type is describe here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target

From what I know it is basically the same as pull_request but works using the target's branch workflow.

IMHO it's only a matter of adding it there:
https://github.com/dflook/terraform-github-actions/blob/444c0ab6bda69bc951b6df2ffb5fa58985466bd8/image/tools/github_pr_comment.py#L78

**Comment by dflook** [comment]
This was added in v1.7.0 🎉
