### ISSUE TITLE
Add ability to use git with HTTP authentication instead of ssh key

### ISSUE THREAD

**Issue by mentos1386** [dflook/terraform-github-actions#56]
We have our terraform modules in a github repository. As it's being private, we use personal tokens to access the shared repository.

We have are using `https://github.com/xxx/terraform/...` as module sources. And then add the following in our github action to make terraform use proper credentials to authenticate.
```
  git config --global \
          url."https://$MODULES_USER:$MODULES_TOKEN@github.com/xxx/terraform".insteadOf \
          https://github.com/xxx/terraform
```
Could there be `git_user`, `git_password`, `git_repository` input variables be exposed that would do that inside your actions?

It might need to be an array or map to facilitate possibility of multiple repositories sources.

**Comment by dflook** [comment]
Hi @mentos1386, v1.10.0 was just released that has a new `TERRAFORM_HTTP_CREDENTIALS` environment variable.

Use can use it with a github personal access token:
```yaml
  env:
    TERRAFORM_HTTP_CREDENTIALS: github.com/<owner>/<repo>=<username>:${{ secrets.USER_PAT }}
```

You can see the details on the terraform-plan [README.md](https://github.com/dflook/terraform-github-actions/tree/master/terraform-plan#environment-variables)
