### ISSUE TITLE
Github comment only if there are changes in the plan

### ISSUE THREAD

**Issue by mkuthan** [dflook/terraform-github-actions#59]
Would you mind to add an option to disable github comment if there is no changes in the plan? 
I do have a plan for multiple TF modules but all modules are in the single workflow to avoid too many plans. Right now I often get many comments like "No changes. Infrastructure is up-to-date." if the effective change was made only for few modules.

BTW. Wonderful actions, thanks!

**Comment by dflook** [comment]
Hello @mkuthan, this has been added in v1.11.0.

With dflook/terraform-plan you can now set the `add_github_comment` input to `changes-only`. This will only add a PR comment if there are changes in the plan.

**Comment by mkuthan** [comment]
Works like a charm - thank you!
