### ISSUE TITLE
Plan not applied (Plan has changed) with Terraform 0.12

### ISSUE THREAD

**Issue by adborden** [dflook/terraform-github-actions#62]
I'm not sure if it was in v1.9.1 or the 1.9.0. We're using Terraform 0.12.30 and our apply action recently started failing with "Plan not applied (Plan has changed)".

PR plan: https://github.com/GSA/datagov-infrastructure-live/pull/141
Apply action: https://github.com/GSA/datagov-infrastructure-live/runs/2423648701?check_suite_focus=true

When I manually diff the plans in each, I get an empty diff.

plan workflow: https://github.com/GSA/datagov-infrastructure-live/blob/2d2cbe437a1732b4975c98b43c049601fe869040/.github/workflows/plan.yml
apply workflow: https://github.com/GSA/datagov-infrastructure-live/blob/2d2cbe437a1732b4975c98b43c049601fe869040/.github/workflows/apply.yml

To work-around, we've started using `auto_approve: true`.

**Comment by adborden** [comment]
We tried pinning to v1.9.0 thinking it was related to the recent release, but we saw the same behavior: https://github.com/GSA/datagov-infrastructure-live/pull/142/files

**Comment by dflook** [comment]
Hello @adborden, there is a fix in v1.9.2 which help, can you give it a try?

**Comment by adborden** [comment]
So far so good! I'm seeing 1.9.2 get pulled in and the last deploy seemed to work. I'll re-open if we see it again. Thank you!
