### ISSUE TITLE
comment changes in plan output - terraform 15.1

### ISSUE THREAD

**Issue by tony-aq** [dflook/terraform-github-actions#64]
Are lines matching `^\s*?#` included with the diff between the plan and apply actions?

I suspect ignoring these "comment lines" during diff is a good solution.

It looks like something changed under the hood in the output of terraform between my plan and apply.

My hunch is that the `# (\d+ unchanged \S+ hidden)` comments are included with the diff causing apply to fail.

In plan output I see:
```
        # (32 unchanged attributes hidden)

      ~ scaling_configuration {
          ~ seconds_until_auto_pause = 300 -> 7200
          ~ timeout_action           = "ForceApplyCapacityChange" -> "RollbackCapacityChange"
            # (3 unchanged attributes hidden)
        }
    }
```

In apply output I see:
```
        # (33 unchanged attributes hidden)

      ~ scaling_configuration {
          ~ seconds_until_auto_pause = 300 -> 7200
          ~ timeout_action           = "ForceApplyCapacityChange" -> "RollbackCapacityChange"
            # (3 unchanged attributes hidden)
        }
    }
```

The apply output fails without clear reason.  The approved plan comment details:
> Plan not applied in Apply #8 (Plan has changed)

**Comment by dflook** [comment]
Hello @tony-aq. You are right, the number of unchanged attributes would be picked up as a change in the plan.

Are you able to tell if the provider version changed between the plan and apply?

**Comment by tony-aq** [comment]
Hello, greetings @dflook!

Yes, the aws provider bumped by a minor revision over the course of a week.  

From:
```
- Installing hashicorp/aws v3.37.0...
- Installed hashicorp/aws v3.37.0 (signed by HashiCorp)
```

To:
```
- Installing hashicorp/aws v3.38.0...
- Installed hashicorp/aws v3.38.0 (signed by HashiCorp)
```

**Comment by dflook** [comment]
Ah ok, it's good we understand why the output changed 😄 . Ignoring the 'comment lines' seems reasonable, I'll have to think about it a bit more.

**Comment by dflook** [comment]
The count of unchanged attributes is now ignored when comparing plans in v1.27.0
