### ISSUE TITLE
`path` input should default to `.`

### ISSUE THREAD

**Issue by adborden** [dflook/terraform-github-actions#78]
The `path` input variable is required. In most of my Terraform projects I have to se this to `path: .`, which feels silly since it's the default in other Terraform GH Actions.

**Comment by dflook** [comment]
Making you feel silly isn't a compelling reason for me to change it.

**Comment by adborden** [comment]
You wouldn't accept a PR for this?

**Comment by adborden** [comment]
Sorry for the extra pings on this. Your initial response was a bit jarring. I didn't realize that opening the issue was asking you to do the work, I was merely asking you to consider it. No point submitting the PR if it's not going to be accepted and I didn't see a CONTRIBUTING or similar guidance, so I assumed this feature request via GH issue was fair game.

I can understand your stance on being explicit, but using sane defaults is also a best practice and it doesn't prevent anyone from being explicit and specifying `.`. If that's still your opinion, that's fine, no response necessary. I just wanted to clarify my justification for the request. Thanks for the consideration.

**Comment by dflook** [comment]
Hi @adborden, It's not a bad idea and i'm still considering it.

**Comment by dflook** [comment]
Hi @adborden, the `path` does now default to the action workspace in v1.14.0
