### ISSUE TITLE
[terraform-plan] Add output for the plan file

### ISSUE THREAD

**Issue by donovanmuller** [dflook/terraform-github-actions#79]
In context of using analysis tools like [Checkov](https://github.com/bridgecrewio/checkov) to scan Terraform plan files, is it possible to add new outputs to the `terraform-plan` action with the plan file contents. 

Ideally in both default and JSON formats (JSON format [required](https://github.com/bridgecrewio/checkov#configure-an-input-folder-or-file) for Checkov).

**Comment by dflook** [comment]
v1.16.0 has just been released which has two new outputs:
  - `json_plan_path` is a path to the generated plan in a JSON format file
  - `text_plan_path` is a path to the generated plan in a human readable text file
